Post: Mise en place de notre système d'abonnement multi-plateforme
etf1/etf1.github.io pull request #52
Opened 2022-02-09 20:23 UTC by eko

2022-02-15 12:33 UTC, fadomire reviewed
C'est intéressant et bien écrit.
Si on veut améliorer encore, je dirais qu'en tant que lecteur d'article de blog tech ce que je veux savoir c'est:
- Quels problèmatiques / caveat ont été rencontrés
- Quelles solutions ont été choisies, lesquelles ont été écartées et pourquoi

En gros, un plan du type:
- Thème
- Problèmes rencontrés
- Solutions évaluées
- Solutions retenues
- Takeaway

Mais clairement ça peut être publié comme ça, c'est déjà intéressant, surtout pour quelqu'un qui voudrait chercher la faille pour avoir un abo gratuit ;)

2022-02-15 12:33 UTC, fadomire commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Dans chacun des cas, nos applications web et mobiles contactent notre gateway GraphQL qui communique ensuite via le protocole [gRPC](https://grpc.io/) avec les différents micro-services.
ça donne envie de savoir pourquoi gRPC

2022-02-15 12:33 UTC, fadomire commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +* Exposer une API permettant de vérifier un abonnement souscri depuis un store mobile (Apple, Google),
souscri > souscrit ?

2022-02-15 12:55 UTC, eko commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Dans chacun des cas, nos applications web et mobiles contactent notre gateway GraphQL qui communique ensuite via le protocole [gRPC](https://grpc.io/) avec les différents micro-services.
Exact, je vais en profiter pour ajouter un lien vers un article existant qui présente l'architecture backend

2022-02-15 12:56 UTC, eko commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +* Abonnement sur iOS via l'[App Store](https://www.apple.com/fr/app-store/) d'Apple.
Je vais ajouter un paragraphe sur le choix de Stripe

2022-02-15 19:34 UTC, eko commented
Merci pour ta review @fadomire !

Je pense que ça dépend beaucoup de l'angle avec lequel tu attaque le sujet : ici l'objectif est clairement d'expliquer comment nous avons mis en place la solution de paiement multi-fournisseur côté backend.

Bien évidemment, j'évoque également quelques problématiques que nous avons rencontrés, notamment la section "Particularités" qui relève certains de ces points.

Aussi, je n'ai pas participé personnellement au choix de la solution Stripe donc je ne vais pas être en mesure d'expliquer pourquoi TF1 a fait ce choix et pas une autre solution.

J'imagine que Stripe a été sélectionné dû au fait qu'il s'agit d'une solution leader sur le marché et qu'ils proposent une grande intégration / personnalisation via leurs APIs et SDKs (j'ai ajouté une petite phrase là-dessus).

2022-03-13 11:24 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Nous avons ensuite commencés à éprouver ce modèle avec le parcours le plus important et le plus complet : celui de Stripe sur le web.
```suggestion
Nous avons ensuite commencé à éprouver ce modèle avec le parcours le plus important et le plus complet : celui de Stripe sur le web.
```

2022-03-13 11:25 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Nous avons ensuite commencés à éprouver ce modèle avec le parcours le plus important et le plus complet : celui de Stripe sur le web.
Je ne suis pas sûr que le parcours stipe soit le plus `important`. Je ne sais pas trop ce que tu entends par là.
Potentiellement on peut parler de parcours le plus `complexe` (car dans les cas des apps, une partie du travaille est délégué aux applications et au store), si c'est ce point que tu veux souligner.

2022-03-13 11:31 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Une fois les abonnements actifs, il nous faut également surveiller les mises à jour de celui-ci :
```suggestion
Une fois les abonnements actifs, il nous faut également surveiller les mises à jour de ceux-ci :
```
Ou
```suggestion
Une fois l'abonnements actif, il nous faut également surveiller les mises à jour de celui-ci :
```

2022-03-13 11:32 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Pour cela, nous avons mis en place des endpoints HTTP pour chaque fournisseur : `/webhook/<provider>` : pour récupérer les événements provenant d'un fournisseur donné
```suggestion
Pour cela, nous avons mis en place des endpoints HTTP pour chaque fournisseur : `/webhook/<provider>` : pour récupérer les événements provenant d'un fournisseur donné.
```

2022-03-13 11:34 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Dans un souci de **robustesse** de traitements de ces événements, trois points sont importants à noter du côté de ces consommateurs afin de limiter tout type d'erreur :
```suggestion
Dans un souci de **robustesse** de traitement de ces événements, trois points sont importants à noter du côté de ces consommateurs afin de limiter tout type d'erreur :
```

2022-03-13 11:35 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +1. Nous avons mis en place un **système de lock** avec [Redis](https://redis.io/), qui expire au bout d'une durée définie (TTL). Cela nous permet de ne nous assurer qu'aucun événement ne puisse se ch
```suggestion
1. Nous avons mis en place un **système de lock** avec [Redis](https://redis.io/), qui expire au bout d'une durée définie (TTL). Cela nous permet de ne nous assurer qu'aucuns événements ne puissent se chevaucher.
```

2022-03-13 11:37 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +La documentation n'est en effet pas toujours bien à jour et certaines valeurs ne sont pas forcément renseignées correctement dans le message, en fonction des événements reçus : nous avons donc passés
```suggestion
La documentation n'est en effet pas toujours bien à jour et certaines valeurs ne sont pas forcément renseignées correctement dans le message, en fonction des événements reçus : nous avons donc passé beaucoup de temps à tester et évaluer les données reçues.
```

2022-03-13 11:37 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Nous avons passés beaucoup de temps à défricher toutes les informations chez les différents fournisseurs afin de pouvoir mettre en place un modèle commun ainsi qu'à comprendre les différents workflow
```suggestion
Nous avons passé beaucoup de temps à défricher toutes les informations chez les différents fournisseurs afin de pouvoir mettre en place un modèle commun ainsi qu'à comprendre les différents workflows mobiles mais nous sommes finalement parvenus à mettre en place un système qui répond à notre besoin.
```

2022-03-13 11:38 UTC, iotafr requested changes
Super boulot ! Merci.
Juste quelques petites coquilles à corriger ;)

2022-03-13 11:40 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Vous l'avez peut-être remarqué si vous êtes un utilisateur MYTF1, nous avons récemment sortis l'offre [MYTF1 MAX](https://www.tf1.fr/offre-max) : une offre payante vous permettant de bénéficier des p
```suggestion
Vous l'avez peut-être remarqué si vous êtes un utilisateur MYTF1, nous avons récemment sorti l'offre [MYTF1 MAX](https://www.tf1.fr/offre-max) : une offre payante vous permettant de bénéficier des programmes avec des fonctionnalités étendues.
```

2022-03-13 11:42 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Pour les abonnements pris depuis le web, plusieurs solutions pouvaient être envisagées. Notre choix s'est porté sur la solution Stripe : un des leaders dans le domaine du paiement en ligne permettant
```suggestion
Pour les abonnements pris depuis le web, plusieurs solutions ont été envisagées. Notre choix s'est porté sur la solution Stripe : un des leaders dans le domaine du paiement en ligne permettant de gérer des abonnements. Aussi, Stripe dispose de solutions d'intégration très complètes (APIs, SDK front).
```

2022-03-13 11:45 UTC, iotafr commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +1. L'utilisateur **saisie ses informations bancaires** sur le front MYTF1 via le SDK [PaymentElement](https://stripe.com/docs/payments/payment-element),
```suggestion
1. L'utilisateur **saisit ses informations bancaires** sur le front MYTF1 via le SDK [PaymentElement](https://stripe.com/docs/payments/payment-element),
```

2022-03-13 16:14 UTC, eko commented on content/post/2022/architecture/abonnement-multi-plateforme/index.md
> +Nous avons ensuite commencés à éprouver ce modèle avec le parcours le plus important et le plus complet : celui de Stripe sur le web.
Oui effectivement c'est bien ce que je voulais sous-entendre mais le mot n'était pas bien choisi ;-)

J'ai re-formulé ainsi en me basant sur ta proposition :
> Nous avons ensuite commencé à éprouver ce modèle avec le parcours le plus complexe : celui de Stripe sur le web car nous gérons nous-même les workflows de création des abonnements, annulation et changement de périodicité, ce qui n'est pas le cas côté application mobile car les abonnements sont gérés par les stores.

2022-03-13 16:15 UTC, eko commented
Merci d'avoir pris le temps de faire une relecture 🙏

2022-03-13 16:30 UTC, iotafr approved these changes
Par contre le merge doit être fait sur develop ;)

2022-03-13 17:55 UTC, merged

2022-03-13 17:55 UTC, eko commented
Merci, c'est mergé sur develop du coup : il faudrait changer la base branche par défaut dans les settings du projet pour la positionner sur `develop`