QA : Argo WF
etf1/etf1.github.io pull request #62
Opened 2024-08-01 12:23 UTC by jbbernard

2024-08-05 13:44 UTC, ffrik-54 requested changes

2024-08-05 13:44 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
> +apiVersion: kustomize.config.k8s.io/v1beta1
Comme tu le vois, on utilise Kustomize pour la gestion des ressources. Cela amener une confusion car on parle plus haut de Helm. Kustomize a été choisi dans notre cas car c'est beaucoup plus simple, avec une courbe d'apprentissage moins élevée, et suffisant pour notre besoin, on cherche à simplifier la maintenance. De plus il est intégré nativement dans "kubectl".
Helm est probablement utilisé côté ops pour des architectures plus complexes.

Tout ça pour te dire qu'il faut juste ajouter une ligne expliquant pourquoi ici c'est Kustomize.

2024-08-05 13:44 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
> +Et on peut ensuite facilement déclarer un workflow complet, avec ces paramètres de lancement custom, toujours grâce à des fichiers YAML, comme par exemple :
avec Ses paramètres non ?

2024-08-05 13:44 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
> +* Miger au profit d'un autre outil
Miger -> Migrer

2024-08-05 15:02 UTC, jbbernard commented on content/post/2024/qa/migration-argo/index.md
> +Et on peut ensuite facilement déclarer un workflow complet, avec ces paramètres de lancement custom, toujours grâce à des fichiers YAML, comme par exemple :
bien vu

2024-08-29 15:46 UTC, ffrik-54 requested changes

2024-08-29 15:46 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
>  2. **Gestion des dépendances et sécurité** : L'utilisation de conteneurs Docker améliore la gestion des dépendances et renforce la sécurité grâce à l'isolation des environnements.
Nous avons besoin d'un outil assez complexe pour gérer de multiples environnements, pouvant déployer/executer à la demande mais aussi avec divers déclencheurs git ou programmés, tout en étant assez simple pour configurés en partie par des ingénieurs automaticiens (non professionnels de la gestion d'infrastructure), avec des ajouts/suppressions/modifications fréquentes de workflows au fur et à mesure des développements à venir, qu'on sait ambitieux, de façon très fluide.  Argo étant basé sur Kubernetes nous offrait à la fois cette flexibilité et cette scalabilité.
Nous avions aussi besoin de garder un historique clair de chaque modification sur les workflows, les infrastructures ou les images, pour assurer la stabilité, la reproductibilité et la fiabilité de nos tests, et pouvoir rollback facilement au moindre soucis, ceci au moindre coût. L'approche GitOps offerte par Argo répond le mieux à notre besoin, elle permet à nos automaticiens, de gérer leur infrastructure, le déploiement de leur application à tester, la compilation et le lancement de leur tests, ainsi que la génération et la communication des rapports, de la même façon qu'ils gèrent l'implémentation de leurs tests, donc avec une courbe d'apprentissage raisonnable. 
Enfin, cela permet d'uniformiser la stack technique de la QA avec le reste des applications métier, soit déjà en Argo, soit par exemple les interactions avec des workflows CI existant en Github Actions seront beaucoup plus naturelles (langage yaml dans les deux cas).

2024-08-29 15:46 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
> +Par sécurité, nous avons d'abord commencé par sélectionné un premier pipeline, celui de tests automatisés du site Web de TFOU MAX. Nous avons traduit le pipeline Jenkins en workflows Argo en utilisan
Par sécurité, nous avons d'abord commencé par sélectionner un premier pipeline, celui de tests automatisés du site Web de TFOU MAX. Nous avons traduit le pipeline Jenkins en workflow Argo en utilisant les briques définies précédemment, et nous l'avons testé dans un environnement de staging. Une fois celui-ci validé, nous avons pu le déployer dans l'environnement de prod, et après 2 semaines de double run, nous avons comparé les résultats entre Jenkins et Argo avant de décider de stopper le pipeline dans Jenkins.\

2024-08-29 15:46 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
> +Puis nous avons décliné cette procédure de migration pipeline par pipeline, avec un double run pour minimiser les risques
Puis nous avons décliné cette procédure de migration pipeline par pipeline, avec un double run pour assurer le fonctionnement.

2024-08-29 15:46 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
> +La migration de Jenkins vers une solution Docker avec Argo Workflow et Argo CD représente une avancée significative pour notre équipe. D'un outil à l'avenir incertain, nous sommes passés à une soluti
"D'un outil à l'avenir incertain" -> "d'un outil risquant de correspondre de moins en moins à nos besoins"
Ici on pourrait comprendre que Jenkins est obsolète "dans l'absolu".
Il y a des cas où on veut avoir des gestionnaires d'infra bien séparés des devs, car on ne va modifier l'app que trois fois dans l'année, où des plugins Jenkins qui collent parfaitement avec nos cas d'usages et offrent une super valeur, où on travaille sur des environnements pas compatibles k8 etc, où Jenkins à son sens.

2024-08-29 15:46 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
>  * **Déploiement déclaratif** : Argo CD utilise Git comme source de vérité, assurant que l'état des applications en production correspond toujours aux configurations définies.
Cette partie fait un peu doublon avec la partie "Pourquoi choisir argo ?" et fait un peu chatgpt.

2024-08-29 15:46 UTC, ffrik-54 commented on content/post/2024/qa/migration-argo/index.md
> +Puis nous avons décliné cette procédure de migration pipeline par pipeline, avec un double run pour minimiser les risques
peut-être compléter cette partie qui apporte de la valeur : 
"Nous avons constaté des temps d'execution à peu près comparables, vérifier la consistance des logs via Datadog"

2024-08-30 07:49 UTC, merged